; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.23918.0 

	TITLE	C:\Users\michalis\Documents\Visual Studio 2015\Projects\MeOS\MeOS\pit.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

_DATA	SEGMENT
COMM	_frequency:DWORD
_DATA	ENDS
PUBLIC	_init_pit_timer
PUBLIC	_play_sound
PUBLIC	_stop_sound
EXTRN	_inportb:PROC
EXTRN	_outportb:PROC
EXTRN	_register_interrupt_handler:PROC
; Function compile flags: /Odtpy
_TEXT	SEGMENT
_temp$ = -1						; size = 1
_stop_sound PROC
; File c:\users\michalis\documents\visual studio 2015\projects\meos\meos\pit.c
; Line 49
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 50
	push	97					; 00000061H
	call	_inportb
	add	esp, 4
	movzx	eax, al
	and	eax, 252				; 000000fcH
	mov	BYTE PTR _temp$[ebp], al
; Line 51
	movzx	ecx, BYTE PTR _temp$[ebp]
	push	ecx
	push	97					; 00000061H
	call	_outportb
	add	esp, 8
; Line 52
	mov	esp, ebp
	pop	ebp
	ret	0
_stop_sound ENDP
_TEXT	ENDS
; Function compile flags: /Odtpy
_TEXT	SEGMENT
_count$ = -8						; size = 2
_cw$ = -2						; size = 1
_speaker_status$ = -1					; size = 1
_frequency$ = 8						; size = 4
_play_sound PROC
; File c:\users\michalis\documents\visual studio 2015\projects\meos\meos\pit.c
; Line 28
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 29
	mov	eax, 1193180				; 001234dcH
	xor	edx, edx
	div	DWORD PTR _frequency$[ebp]
	mov	WORD PTR _count$[ebp], ax
; Line 32
	mov	BYTE PTR _cw$[ebp], 182			; 000000b6H
; Line 33
	movzx	eax, BYTE PTR _cw$[ebp]
	push	eax
	push	67					; 00000043H
	call	_outportb
	add	esp, 8
; Line 35
	movzx	ecx, BYTE PTR _count$[ebp]
	push	ecx
	push	66					; 00000042H
	call	_outportb
	add	esp, 8
; Line 36
	movzx	edx, WORD PTR _count$[ebp]
	sar	edx, 8
	push	edx
	push	66					; 00000042H
	call	_outportb
	add	esp, 8
; Line 38
	push	97					; 00000061H
	call	_inportb
	add	esp, 4
	mov	BYTE PTR _speaker_status$[ebp], al
; Line 39
	movzx	eax, BYTE PTR _speaker_status$[ebp]
	movzx	ecx, BYTE PTR _speaker_status$[ebp]
	or	ecx, 3
	cmp	eax, ecx
	je	SHORT $LN1@play_sound
; Line 44
	movzx	edx, BYTE PTR _speaker_status$[ebp]
	or	edx, 3
	push	edx
	push	97					; 00000061H
	call	_outportb
	add	esp, 8
$LN1@play_sound:
; Line 46
	mov	esp, ebp
	pop	ebp
	ret	0
_play_sound ENDP
_TEXT	ENDS
; Function compile flags: /Odtpy
_TEXT	SEGMENT
_count$ = -8						; size = 2
_h$ = -3						; size = 1
_l$ = -2						; size = 1
_cw$ = -1						; size = 1
__frequency$ = 8					; size = 4
_callback$ = 12						; size = 4
_init_pit_timer PROC
; File c:\users\michalis\documents\visual studio 2015\projects\meos\meos\pit.c
; Line 6
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 7
	mov	eax, DWORD PTR _callback$[ebp]
	push	eax
	push	32					; 00000020H
	call	_register_interrupt_handler
	add	esp, 8
; Line 9
	mov	ecx, DWORD PTR __frequency$[ebp]
	mov	DWORD PTR _frequency, ecx
; Line 12
	mov	eax, 1193180				; 001234dcH
	xor	edx, edx
	div	DWORD PTR __frequency$[ebp]
	mov	WORD PTR _count$[ebp], ax
; Line 15
	mov	BYTE PTR _cw$[ebp], 52			; 00000034H
; Line 17
	movzx	edx, BYTE PTR _cw$[ebp]
	push	edx
	push	67					; 00000043H
	call	_outportb
	add	esp, 8
; Line 19
	movzx	eax, WORD PTR _count$[ebp]
	and	eax, 255				; 000000ffH
	mov	BYTE PTR _l$[ebp], al
; Line 20
	movzx	ecx, WORD PTR _count$[ebp]
	sar	ecx, 8
	and	ecx, 255				; 000000ffH
	mov	BYTE PTR _h$[ebp], cl
; Line 22
	movzx	edx, BYTE PTR _l$[ebp]
	push	edx
	push	64					; 00000040H
	call	_outportb
	add	esp, 8
; Line 23
	movzx	eax, BYTE PTR _h$[ebp]
	push	eax
	push	64					; 00000040H
	call	_outportb
	add	esp, 8
; Line 24
	mov	esp, ebp
	pop	ebp
	ret	0
_init_pit_timer ENDP
_TEXT	ENDS
END
