; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.23918.0 

	TITLE	C:\Users\michalis\Documents\Visual Studio 2015\Projects\MeOS\MeOS\timer.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	_ticks
_BSS	SEGMENT
_ticks	DD	01H DUP (?)
_BSS	ENDS
CONST	SEGMENT
$SG2837	DB	'%u', 00H
CONST	ENDS
PUBLIC	_timer_callback
PUBLIC	_sleep
PUBLIC	_millis
PUBLIC	??0Timer@@QAE@XZ				; Timer::Timer
PUBLIC	?Restart@Timer@@QAEIXZ				; Timer::Restart
PUBLIC	?GetElapsedMillis@Timer@@QAEIXZ			; Timer::GetElapsedMillis
EXTRN	_SetCursor:PROC
EXTRN	_printf:PROC
EXTRN	_cursorX:WORD
EXTRN	_cursorY:WORD
EXTRN	_SCREEN_HEIGHT:BYTE
EXTRN	_frequency:DWORD
; Function compile flags: /Odtpy
_TEXT	SEGMENT
_this$ = -4						; size = 4
?GetElapsedMillis@Timer@@QAEIXZ PROC			; Timer::GetElapsedMillis
; _this$ = ecx
; File c:\users\michalis\documents\visual studio 2015\projects\meos\meos\timer.cpp
; Line 40
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 41
	call	_millis
	mov	ecx, DWORD PTR _this$[ebp]
	sub	eax, DWORD PTR [ecx]
; Line 42
	mov	esp, ebp
	pop	ebp
	ret	0
?GetElapsedMillis@Timer@@QAEIXZ ENDP			; Timer::GetElapsedMillis
_TEXT	ENDS
; Function compile flags: /Odtpy
_TEXT	SEGMENT
_temp$ = -8						; size = 4
_this$ = -4						; size = 4
?Restart@Timer@@QAEIXZ PROC				; Timer::Restart
; _this$ = ecx
; File c:\users\michalis\documents\visual studio 2015\projects\meos\meos\timer.cpp
; Line 33
	push	ebp
	mov	ebp, esp
	sub	esp, 8
	mov	DWORD PTR _this$[ebp], ecx
; Line 34
	mov	ecx, DWORD PTR _this$[ebp]
	call	?GetElapsedMillis@Timer@@QAEIXZ		; Timer::GetElapsedMillis
	mov	DWORD PTR _temp$[ebp], eax
; Line 35
	call	_millis
	mov	ecx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [ecx], eax
; Line 36
	mov	eax, DWORD PTR _temp$[ebp]
; Line 37
	mov	esp, ebp
	pop	ebp
	ret	0
?Restart@Timer@@QAEIXZ ENDP				; Timer::Restart
_TEXT	ENDS
; Function compile flags: /Odtpy
_TEXT	SEGMENT
_this$ = -4						; size = 4
??0Timer@@QAE@XZ PROC					; Timer::Timer
; _this$ = ecx
; File c:\users\michalis\documents\visual studio 2015\projects\meos\meos\timer.cpp
; Line 28
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 29
	call	_millis
	mov	ecx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [ecx], eax
; Line 30
	mov	eax, DWORD PTR _this$[ebp]
	mov	esp, ebp
	pop	ebp
	ret	0
??0Timer@@QAE@XZ ENDP					; Timer::Timer
_TEXT	ENDS
; Function compile flags: /Odtpy
_TEXT	SEGMENT
_millis	PROC
; File c:\users\michalis\documents\visual studio 2015\projects\meos\meos\timer.cpp
; Line 17
	push	ebp
	mov	ebp, esp
; Line 18
	imul	eax, DWORD PTR _ticks, 1000
	xor	edx, edx
	div	DWORD PTR _frequency
; Line 19
	pop	ebp
	ret	0
_millis	ENDP
_TEXT	ENDS
; Function compile flags: /Odtpy
_TEXT	SEGMENT
_start$ = -4						; size = 4
__time$ = 8						; size = 4
_sleep	PROC
; File c:\users\michalis\documents\visual studio 2015\projects\meos\meos\timer.cpp
; Line 22
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 23
	call	_millis
	mov	DWORD PTR _start$[ebp], eax
$LN2@sleep:
; Line 24
	call	_millis
	sub	eax, DWORD PTR _start$[ebp]
	cmp	eax, DWORD PTR __time$[ebp]
	jae	SHORT $LN1@sleep
	jmp	SHORT $LN2@sleep
$LN1@sleep:
; Line 25
	mov	esp, ebp
	pop	ebp
	ret	0
_sleep	ENDP
_TEXT	ENDS
; Function compile flags: /Odtpy
_TEXT	SEGMENT
_x$ = -8						; size = 2
_y$ = -4						; size = 2
_regs$ = 8						; size = 64
_timer_callback PROC
; File c:\users\michalis\documents\visual studio 2015\projects\meos\meos\timer.cpp
; Line 7
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 8
	mov	eax, DWORD PTR _ticks
	add	eax, 1
	mov	DWORD PTR _ticks, eax
; Line 9
	mov	cx, WORD PTR _cursorX
	mov	WORD PTR _x$[ebp], cx
	mov	dx, WORD PTR _cursorY
	mov	WORD PTR _y$[ebp], dx
; Line 11
	movzx	eax, BYTE PTR _SCREEN_HEIGHT
	sub	eax, 2
	push	eax
	push	0
	call	_SetCursor
	add	esp, 8
; Line 12
	mov	ecx, DWORD PTR _ticks
	push	ecx
	push	OFFSET $SG2837
	call	_printf
	add	esp, 8
; Line 13
	movzx	edx, WORD PTR _y$[ebp]
	push	edx
	movzx	eax, WORD PTR _x$[ebp]
	push	eax
	call	_SetCursor
	add	esp, 8
; Line 14
	mov	esp, ebp
	pop	ebp
	ret	0
_timer_callback ENDP
_TEXT	ENDS
END
